@startuml

start
while (paquete disponible?)
  if (paquete IPv4 fragmentado?) then (si)

    if (existe flujo de red relacionado?) then (no)
      :actualizar flujo de red;
    else (no)
      :crear flujo de red;
    endif
    
    :intentar reensamblar paquete IPv4;
  else (no)
  endif

  if (paquete válido?) then (si)
    if (existe flujo de transporte relacionado?) then (si)
      :actualizar flujo de transporte;
    else (no)
      :crear flujo de transporte;
    endif
  else (no)
  endif

  while (existe flujo de red antiguo?)
    :cerrar flujo de red más antiguo;
  endwhile

  while (existe flujo de transporte antiguo?)
    :cerrar flujo de transporte más antiguo;
  endwhile
endwhile

while (existe flujo de transporte?)
  :cerrar flujo de transporte más antiguo;
endwhile

stop
@enduml
