@startuml

start
while (paquete disponible?) is (si)
  if (paquete IPv4 fragmentado?) then (si)

    if (existe flujo de red relacionado?) then (si)
      :actualizar flujo de red;
    else (no)
      :crear flujo de red;
    endif
    
    :intentar reensamblar paquete IPv4;
  else (no)
  endif

  if (paquete válido?) then (si)
    if (existe flujo de transporte relacionado?) then (si)
      :actualizar flujo de transporte;
    else (no)
      :crear flujo de transporte;
    endif
  else (no)
  endif

  while (existe flujo de red antiguo?) is (si)
    :cerrar flujo de red más antiguo;
  endwhile (no)

  while (existe flujo de transporte antiguo?) is (si)
    :cerrar flujo de transporte más antiguo;
  endwhile (no)
endwhile (no)

while (existe flujo de transporte?) is (si)
  :cerrar flujo de transporte más antiguo;
endwhile (no)

stop
@enduml
